package com.example.lenovo.myproject1210.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lenovo.myproject1210.Cache;

import com.example.lenovo.myproject1210.greendao.CacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheDaoConfig;

    private final CacheDao cacheDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheDaoConfig = daoConfigMap.get(CacheDao.class).clone();
        cacheDaoConfig.initIdentityScope(type);

        cacheDao = new CacheDao(cacheDaoConfig, this);

        registerDao(Cache.class, cacheDao);
    }
    
    public void clear() {
        cacheDaoConfig.clearIdentityScope();
    }

    public CacheDao getCacheDao() {
        return cacheDao;
    }

}
